---

- name: Get cluster api_groups
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups')}}"

- name: Make nginx config configmap state={{ state }}
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'nginx-config.configmap.yaml.j2') | from_yaml }}"
  notify: kill nginx pods

- name: Make deployment state={{ state }}
  k8s:
    state: "{{ state }}"
    merge_type: merge
    definition: "{{ lookup('template', 'deployment.yaml.j2') | from_yaml }}"

- name: Make service state={{ state }}
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'service.yaml.j2') | from_yaml }}"

- name: Make route state={{ state }}
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'route.yaml.j2') | from_yaml }}"
  when: ('route.openshift.io' in api_groups) | bool
