---

- name: Get cluster api_groups
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups')}}"

- name: Make deployment state={{ state }}
  k8s:
    state: "{{ state }}"
    namespace: "{{ namespace }}"
    definition: "{{ lookup('file', 'deployment.yaml') | from_yaml }}"

- name: Make service state={{ state }}
  k8s:
    state: "{{ state }}"
    namespace: "{{ namespace }}"
    definition: "{{ lookup('file', 'service.yaml') | from_yaml }}"

- name: Make route state={{ state }}
  k8s:
    state: "{{ state }}"
    namespace: "{{ namespace }}"
    definition: "{{ lookup('file', 'route.yaml') | from_yaml }}"
  when: ('route.openshift.io' in api_groups) | bool
