---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        # https://torstenwalter.de/openshift/nginx/2017/08/04/nginx-on-openshift.html
        image: twalter/openshift-nginx:stable
        ports:
        - containerPort: 8081
